### PR TITLE
Fix e2e tests

### LINKED ISSUE #26: Fix end to end tests

### PR DESCRIPTION
**Pull request by ConcernedHobbit**
Closes #26

### CODE REVIEW

File: middleware.ts [hunk 1]
```diff
@@ -39,16 +40,6 @@ export const middleware = (req: NextRequest) => {
         return response
     }
 
-    // Redirect if the locale in the path does match the preferred language
-    if (!path.startsWith(`/${lang}/`) && !(path === `/${lang}`)) {
```
Comment (ConcernedHobbit) [inline middleware.ts:43]: Hot take: nah. If I go to `courses.tko-aly.fi/en/TKT/20-23`, I expect it to be in English, even if my cookie is set to Finnish.

Comment (ConcernedHobbit) [reply middleware.ts:43]: We _could_ use this, but then we would need to make sure E2E tests always have the cookie set to a specific language.

**Comment by ConcernedHobbit** [comment]
That green check is so darn beautiful.

... next we need more meaningful E2E tests :D That aren't flaky to graph changes.
